package learning

class Filters (
              val a: Int,
              val b: Int,
              val c: Int,
              val d: Int,
              val e: Int,
              val f: Int,
              val g: Int,
              val h: Int,
              val i: Int,
              val j: Int,
              val k: Int,
              val l: Int,
              val m: Int,
              val n: Int,
              val o: Int,
              val p: Int,
              val q: Int,
              val r: Int,
              val s: Int,
              val t: Int,
              val u: Int,
              val v: Int,
              val w: Int,
              val x: Int,
              val z: Int
              ) {

  def copy(
   a: Int = this.a,
   b: Int = this.b,
   c: Int = this.c,
   d: Int = this.d,
   e: Int = this.e,
   f: Int = this.f,
   g: Int = this.g,
   h: Int = this.h,
   i: Int = this.i,
   j: Int = this.j,
   k: Int = this.k,
   l: Int = this.l,
   m: Int = this.m,
   n: Int = this.n,
   o: Int = this.o,
   p: Int = this.p,
   q: Int = this.q,
   r: Int = this.r,
   s: Int = this.s,
   t: Int = this.t,
   u: Int = this.u,
   v: Int = this.v,
   w: Int = this.w,
   x: Int = this.x,
   z: Int = this.z
          ): Filters =
    new Filters(
      a,
      b,
      c,
      d,
      e,
      f,
      g,
      h,
      i,
      j,
      k,
      l,
      m,
      n,
      o,
      p,
      q,
      r,
      s,
      t,
      u,
      v,
      w,
      x,
      z
  )

}